<a href="https://colab.research.google.com/github/prativap1/Dataproassignment/blob/main/dataproAssign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1) Generate an array of zeroes using inbuilt numpy function.

 



In [1]:
import numpy as np
a = np.zeros(10)
print (a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 2) Run the given code and find the dot product of both arrays.

In [2]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)


[[6 6 8 3]
 [8 3 4 8]
 [8 7 6 4]]
[[2 2 6]
 [5 6 8]
 [9 4 4]
 [6 3 6]]


In [3]:
a.dot(b)

array([[132,  89, 134],
       [115,  74, 136],
       [129,  94, 152]])

In [4]:
b.dot(a)

array([[ 76,  60,  60,  46],
       [142, 104, 112,  95],
       [118,  94, 112,  75],
       [108,  87,  96,  66]])

# 3)Read the csv file provided using pandas and display the first 5 entries

In [34]:
import pandas as pd
data =pd.read_csv('/content/data.csv')
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

# 4)Describe the data with all features.

In [6]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


# 5)Find the total count of missing values for each feature.

In [8]:
data.isna().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [9]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

# 6)Display all the unique values from the 'DESCRIPTION’ column.

In [14]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

# 7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [17]:
df=data.groupby('DESCRIPTION').mean()
df

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

# 8)Generate a random sample of 10 rows from the data.

In [18]:
a = data.sample(n=10)
a

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357
10        31                  Little Missouri State Park  ...   0.003136   0.313756
14        33                     Turtle River State Park  ...   0.000378   0.145220
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800

[10 rows x 6 columns]


# 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

 



In [24]:
np.random.rand(4)

array([0.5759549 , 0.21463387, 0.62322383, 0.8412897 ])

In [21]:
data['New_feature']=np.random.rand(25)
data['New_feature']

0     0.665313
1     0.393252
2     0.719512
3     0.050223
4     0.715381
5     0.833643
6     0.896094
7     0.731994
8     0.924059
9     0.670048
10    0.553923
11    0.140884
12    0.230989
13    0.670483
14    0.030211
15    0.377780
16    0.142849
17    0.057018
18    0.743661
19    0.548842
20    0.569820
21    0.415661
22    0.528833
23    0.734125
24    0.198743
Name: New_feature, dtype: float64

# 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [27]:
data.OBJECTID=data.OBJECTID.replace(0,data.OBJECTID.mean())
data.OBJECTID

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64

In [29]:
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.LEN  New_feature
0        21        Fort Stevenson State Park  ...  0.135641     0.665313
1        22           Beaver Lake State Park  ...  0.080067     0.393252
2        23  Fort Abraham Lincoln State Park  ...  0.119868     0.719512
3        24           Fort Ransom State Park  ...  0.128733     0.050223
4        25        Grahams Island State Park  ...  0.125546     0.715381

[5 rows x 7 columns]